# Generated by Django 4.1.7 on 2023-07-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
    ]
